import { useState } from 'react';

function SessionControls({ user, onStartSession, onStopSession, sessionActive, wsConnected }) {
  const [interventionType, setInterventionType] = useState('auditory');
  const [soundVolume, setSoundVolume] = useState(50);
  const [taskContext, setTaskContext] = useState('');
  const [loading, setLoading] = useState(false);

  const handleStartSession = async () => {
    if (!taskContext.trim()) {
      alert('Please enter a task context (e.g., "Reading", "Studying")');
      return;
    }

    setLoading(true);
    try {
      await onStartSession({
        interventionType,
        taskContext,
        soundVolume
      });
    } catch (error) {
      console.error('Error starting session:', error);
      alert('Failed to start session. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleStopSession = async () => {
    setLoading(true);
    try {
      await onStopSession();
    } catch (error) {
      console.error('Error stopping session:', error);
      alert('Failed to stop session. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-slate-800 border border-slate-700 rounded-lg shadow-lg p-6">
      <h3 className="text-lg font-semibold text-white mb-4">Session Controls</h3>

      {/* Connection Status */}
      <div className="mb-6 p-3 rounded-lg bg-slate-900 border border-slate-700">
        <div className="flex items-center justify-between">
          <span className="text-sm font-medium text-gray-300">WebSocket Status:</span>
          <div className="flex items-center space-x-2">
            <div className={`w-2 h-2 rounded-full ${wsConnected ? 'bg-green-500' : 'bg-red-500'}`} />
            <span className={`text-sm font-semibold ${wsConnected ? 'text-green-400' : 'text-red-400'}`}>
              {wsConnected ? 'Connected' : 'Disconnected'}
            </span>
          </div>
        </div>
      </div>

      {!sessionActive ? (
        <div className="space-y-4">
          {/* Task Context */}
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Task Context *
            </label>
            <input
              type="text"
              value={taskContext}
              onChange={(e) => setTaskContext(e.target.value)}
              placeholder="e.g., Reading, Studying, Working"
              className="w-full px-3 py-2 bg-slate-900 border border-slate-600 text-white placeholder-gray-500 rounded-md focus:ring-purple-500 focus:border-purple-500"
              disabled={!wsConnected}
            />
          </div>

          {/* Intervention Type */}
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Intervention Type
            </label>
            <select
              value={interventionType}
              onChange={(e) => setInterventionType(e.target.value)}
              className="w-full px-3 py-2 bg-slate-900 border border-slate-600 text-white rounded-md focus:ring-purple-500 focus:border-purple-500"
              disabled={!wsConnected}
            >
              <option value="none">None (Monitor Only)</option>
              <option value="auditory">Auditory (Sound Feedback)</option>
              <option value="visual">Visual Feedback</option>
              <option value="haptic">Haptic Feedback</option>
              <option value="multi-modal">Multi-Modal</option>
            </select>
            <p className="mt-1 text-xs text-gray-400">
              Sound will be generated by Python pipeline for minimal latency
            </p>
          </div>

          {/* Sound Volume */}
          {interventionType !== 'none' && (
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Maximum Sound Volume: {soundVolume}%
              </label>
              <input
                type="range"
                min="0"
                max="100"
                value={soundVolume}
                onChange={(e) => setSoundVolume(parseInt(e.target.value))}
                className="w-full accent-purple-500"
                disabled={!wsConnected}
              />
              <div className="flex justify-between text-xs text-gray-400 mt-1">
                <span>Silent</span>
                <span>Maximum</span>
              </div>
            </div>
          )}

          {/* Start Button */}
          <button
            onClick={handleStartSession}
            disabled={!wsConnected || loading}
            className="w-full bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white font-bold py-4 px-6 rounded-xl disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 transform hover:scale-105 shadow-xl hover:shadow-2xl flex items-center justify-center space-x-3"
          >
            {loading ? (
              <>
                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-white"></div>
                <span className="text-lg">Starting...</span>
              </>
            ) : (
              <>
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M6.3 2.841A1.5 1.5 0 004 4.11V15.89a1.5 1.5 0 002.3 1.269l9.344-5.89a1.5 1.5 0 000-2.538L6.3 2.84z" />
                </svg>
                <span className="text-lg">Start EEG Session</span>
              </>
            )}
          </button>

          {!wsConnected && (
            <p className="text-sm text-red-400 text-center">
              Connect to WebSocket server to start session
            </p>
          )}
        </div>
      ) : (
        <div className="space-y-4">
          {/* Session Info */}
          <div className="p-4 bg-green-900/30 border border-green-700 rounded-lg">
            <h4 className="font-semibold text-green-300 mb-2">Active Session</h4>
            <div className="space-y-1 text-sm text-green-200">
              <p><strong>Task:</strong> {taskContext}</p>
              <p><strong>Intervention:</strong> {interventionType}</p>
              {interventionType !== 'none' && (
                <p><strong>Max Volume:</strong> {soundVolume}%</p>
              )}
            </div>
          </div>

          {/* Stop Button */}
          <button
            onClick={handleStopSession}
            disabled={loading}
            className="w-full bg-gradient-to-r from-red-500 to-pink-600 hover:from-red-600 hover:to-pink-700 text-white font-bold py-4 px-6 rounded-xl disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 transform hover:scale-105 shadow-xl hover:shadow-2xl flex items-center justify-center space-x-3"
          >
            {loading ? (
              <>
                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-white"></div>
                <span className="text-lg">Stopping...</span>
              </>
            ) : (
              <>
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8 7a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V8a1 1 0 00-1-1H8z" clipRule="evenodd" />
                </svg>
                <span className="text-lg">Stop Session</span>
              </>
            )}
          </button>

          {/* Warning */}
          <p className="text-xs text-gray-400 text-center">
            Session data will be automatically saved when stopped
          </p>
        </div>
      )}

      {/* Instructions */}
      <div className="mt-6 p-4 bg-purple-900/30 border border-purple-700 rounded-lg">
        <h4 className="text-sm font-semibold text-purple-300 mb-2">📋 Instructions</h4>
        <ol className="text-xs text-purple-200 space-y-1 list-decimal list-inside">
          <li>Ensure Python EEG pipeline is running</li>
          <li>Put on EEG headset and check signal quality</li>
          <li>Enter your task context and preferences</li>
          <li>Click "Start EEG Session" to begin</li>
          <li>Focus on your task - sound will adjust automatically</li>
          <li>Click "Stop Session" when complete</li>
        </ol>
      </div>
    </div>
  );
}

export default SessionControls;
